name: 💔 Broken Page
description: Report broken pages
title: "[Broken Page]: "
labels: ["broken"]

body:
  - type: markdown
    attributes:
      value: |
              ***If you can fix it, consider creating a PR. That would be appreciated.***

  - type: textarea
    id: description
    attributes:
      label: Which Page is broken ?
      description: Name of the phishing page which is broken. Attach screenshot if possible.
    validations:
      required: true
