name: 🚀 Feature Request
description: Suggest an idea for improving zphisher
# title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Is your proposal related to a problem?
      description: Provide a clear and concise description of what the problem is.

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: Provide a clear and concise description of what you want to happen.

  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: |
                    Is there anything else you can add about the proposal?
                    *You might want to link to related issues here, if you haven't already.*

  - type: markdown
    attributes:
      value: |
              ***If you can implement the code, consider creating a pull request.*** *Thanks for taking the time to fill out this report!*
